### PR TITLE
Leads support

### PR DESCRIPTION
**Pull request by mvk**
adding leads. please review.

### CODE REVIEW

**Comment by mvk** [comment]
If this smells ok, I'll add tags and lead sources too. Actually, there's no shame of reusing official basecrm SDK... don't you think ?

**Comment by hugorodgerbrown** [comment]
Sounds OK, not sure why Marcel didn't use it - may be worth checking in with him first - will Ling him a note today.

**Comment by hugorodgerbrown** [comment]
Or even ping him a note.

**Comment by stevejalim** [comment]
Sure - tho I think this is good to merge anyway - our use of it won’t be
affected, I think

**Comment by hugorodgerbrown** [comment]
Thinking back on it - when we originally integrated with Base the API was pre-release, so there probably wasn't an SDK. @marcelkornblum - is this correct?

**Comment by marcelkornblum** [comment]
I don't think Base had an SDK when we integrated, no. But their API is
__bad__ so our integration is too. I believe they implemented upsert now,
which should allow us to blast data over in a more confident way.

I also had it in mind that we could rewrite the integration to be a bit
cleverer about statuses; right now an event triggers a specific method call
that tells Base the 'stage' the 'deal' is at; what would be better would be
for the object on our system to interrogate its status and figure the stage
out properly, so we'd just tell it to update itself.

That way it wouldn't matter if queue issues caused calls out of order, and
we'd be able to rewind a deal's status in a few edge cases where right now
Base will be ahead of us. I think this stuff is in a tech debt card
somewhere...

Just in case you fancy rewriting the integration :)

**Comment by mvk** [comment]
Thanks for the update, @marcelkornblum.
I've resorted to the official python client to implement my project (leads addition tool). i.e. I'm currently handling only the leads.
The next phase of the project will access the deals, IMHO in a periodic manner, most probably by queue processing means a'la celery periodic tasks, and the rest would probably be done manually.

Yet, if the income of this project justifies the means, there's a chance I will implement bi-directional connectivity: a deal stage transition would trigger an action on my app, and that app would update new/old stage details.
Then I might get back to this project, and hack on it a bit.
So: no promises in the meanwhile.

**Pull request merged**
